restapi:
    resource: "@RestapiBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AppBundle:Oauthsecurity:login }

app_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AppBundle:Oauthsecurity:loginCheck }

